name: Windows

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-cygwin" 

jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe --login -o igncr '{0}'
    strategy:
      matrix:
        arch: [x86_64]
        platform: [windows]
    steps:
      - name: Msgmerge fix
        shell: pwsh 
        run: |
          Remove-Item "C:\Program Files\Git\usr\bin\msgmerge.exe"

      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: wget

      - name: Install apt-cyg 
        run: |
          wget rawgit.com/transcode-open/apt-cyg/master/apt-cyg -O apt-cyg
          install apt-cyg /bin
     
      - name: Install libs for Ocaml
        run: |
          apt-cyg install gcc-core flexdll binutils cmake gcc-g++ automake autoconf libtool python flex bison coreutils opam 
      
      - name: Install PCRE2
        run: |
          git clone https://github.com/PhilipHazel/pcre2.git
          cd pcre2
          git reset --hard 111cd470b55d0c06bfb157c8f4521907d3d95fdb
          autoreconf -i
          ./configure --prefix=/usr
          make && make install
          cp /usr/lib/pkgconfig/libpcre2-8.pc /usr/share/pkgconfig/
          cp /usr/lib/pkgconfig/libpcre2-posix.pc /usr/share/pkgconfig/

      - name: Install Ocaml
        run: |
          rm -rf /usr/lib/ocaml/
          git clone https://github.com/ocaml/ocaml.git
          cd ocaml
          git checkout 4.14
          git submodule update --init --recursive
          ./configure --enable-imprecise-c99-float-ops --prefix=/usr
          make
          make install
      
      - name: Install libs for opam
        run: |
          apt-cyg install ocaml-dune ocaml-findlib
      
      - name: Install opam
        if: false
        run: |
          curl -OL https://github.com/ocaml/opam/archive/refs/tags/2.1.2.tar.gz
          tar -xzf 2.1.2.tar.gz
          cd opam-2.1.2
          dune external-lib-deps --missing --root . --promote-install-files --profile release opam-installer.install opam.install
          ./configure  --prefix=/usr
          make lib-ext 
          make install

      - name: Install stdlib-shims
        if: false
        run: |
          opam init
          opam install stdlib-shims

      - name: Install libs for Hivex
        run: |
          apt-cyg install cpio  libiconv libiconv-devel gettext  po4a ncurses   ninja genisoimage   byacc libncurses-devel git mingw64-x86_64-gettext lynx gperf 

      - name: Install Hivex 
        run: |
          pkg-config --variable pc_path pkg-config

          git clone https://github.com/kymano-app/libguestfs.git
          cd libguestfs
          curl -OL https://download.libguestfs.org/hivex/hivex-1.3.21.tar.gz
          tar -xzf hivex-1.3.21.tar.gz
          cd hivex-1.3.21
          
          rm -rf ./aclocal.m4
          aclocal
          
          patch ./images/Makefile.am  ../hivex-patches-hivex-1.3.21-2/images/Makefile.am.patch
          autoreconf -i --force
          
          ./configure CFLAGS="-Wno-error=implicit-function-declaration" --disable-ruby --disable-nls --disable-python --disable-perl --disable-ocaml

          make CFLAGS="-v -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/ -I/home/runneradmin/hivex-1.3.21/gnulib/lib -I/home/runneradmin/hivex-1.3.21/ -I/home/runneradmin/hivex-1.3.21/lib -Wno-error=implicit-function-declaration"
          make install

          cp /usr/local/lib/pkgconfig/hivex.pc /usr/share/pkgconfig/
      
      - name: Install libs for Augeas
        run: |
          apt-cyg install gettext-devel libtirpc-devel libreadline-devel libxml2-devel findutils-debuginfo wget

      - name: Install augeas 
        run: |
          cd libguestfs
          git clone https://github.com/hercules-team/augeas.git
          cd augeas
          git reset --hard 002b2d5b60c72da6f3326dfec72152b228a8357d
          patch ./src/transform.c  ../augeas-patches/src/transform.c.patch
          ./autogen.sh
          make && make install
          cp /usr/local/lib/pkgconfig/augeas.pc /usr/share/pkgconfig/

      - name: Install libs for Libguestfs
        run: |
          apt-cyg install file-devel libjansson-devel

      - name: Install Libguestfs
        run: |
          cd libguestfs

          curl -OL https://download.libguestfs.org/1.44-stable/libguestfs-1.44.2.tar.gz
          tar -xzf libguestfs-1.44.2.tar.gz
          cd libguestfs-1.44.2

          patch align/Makefile.am ../libguestfs-patches-1.44.2-2/align/Makefile.am.patch
          patch cat/Makefile.am ../libguestfs-patches-1.44.2-2/cat/Makefile.am.patch
          patch common/protocol/guestfs_protocol.c ../libguestfs-patches-1.44.2-2/common/protocol/guestfs_protocol.c.patch
          patch df/Makefile.am ../libguestfs-patches-1.44.2-2/df/Makefile.am.patch
          patch diff/Makefile.am ../libguestfs-patches-1.44.2-2/diff/Makefile.am.patch
          patch docs/Makefile.am ../libguestfs-patches-1.44.2-2/docs/Makefile.am.patch
          patch edit/Makefile.am ../libguestfs-patches-1.44.2-2/edit/Makefile.am.patch
          patch format/Makefile.am ../libguestfs-patches-1.44.2-2/format/Makefile.am.patch
          patch inspector/Makefile.am ../libguestfs-patches-1.44.2-2/inspector/Makefile.am.patch
          patch lib/inspect-apps.c ../libguestfs-patches-1.44.2-2/lib/inspect-apps.c.patch
          patch m4/guestfs-progs.m4 ../libguestfs-patches-1.44.2-2/m4/guestfs-progs.m4.patch
          patch make-fs/Makefile.am ../libguestfs-patches-1.44.2-2/make-fs/Makefile.am.patch
          patch ocaml/examples/Makefile.am ../libguestfs-patches-1.44.2-2/ocaml/examples/Makefile.am.patch
          patch test-tool/test-tool.c ../libguestfs-patches-1.44.2-2/test-tool/test-tool.c.patch
          patch configure.ac ../libguestfs-patches-1.44.2-2/configure.ac.patch
          patch generator/pr.ml ../libguestfs-patches-1.44.2-2-win/generator/pr.ml.patch
          patch generator/Makefile.am ../libguestfs-patches-1.44.2-2-win/generator/Makefile.am.patch
          patch ocaml/Makefile.am ../libguestfs-patches-1.44.2-2-win/ocaml/Makefile.am.patch
          patch test-data/Makefile.am ../libguestfs-patches-1.44.2-2-win/test-data/Makefile.am.patch
          patch fuse/Makefile.am ../libguestfs-patches-1.44.2-2-win/fuse/Makefile.am.patch
          patch test-tool/Makefile.am ../libguestfs-patches-1.44.2-2-win/test-tool/Makefile.am.patch
          patch fish/Makefile.am ../libguestfs-patches-1.44.2-2-win/fish/Makefile.am.patch
          patch ruby/Makefile.am ../libguestfs-patches-1.44.2-2-win/ruby/Makefile.am.patch
          patch bash/Makefile.am ../libguestfs-patches-1.44.2-2-win/bash/Makefile.am.patch
          patch golang/Makefile.am ../libguestfs-patches-1.44.2-2-win/golang/Makefile.am.patch
          patch rescue/Makefile.am ../libguestfs-patches-1.44.2-2-win/rescue/Makefile.am.patch
          patch python/Makefile.am ../libguestfs-patches-1.44.2-2-win/python/Makefile.am.patch
          patch rust/Makefile.am ../libguestfs-patches-1.44.2-2-win/rust/Makefile.am.patch
          patch java/Makefile.am ../libguestfs-patches-1.44.2-2-win/java/Makefile.am.patch
          patch haskell/Makefile.am ../libguestfs-patches-1.44.2-2-win/haskell/Makefile.am.patch
          patch lib/Makefile.am ../libguestfs-patches-1.44.2-2-win/lib/Makefile.am.patch
          patch Makefile.am ../libguestfs-patches-1.44.2-2-win/Makefile.am.patch
          patch erlang/Makefile.am ../libguestfs-patches-1.44.2-2-win/erlang/Makefile.am.patch
          patch gobject/Makefile.am ../libguestfs-patches-1.44.2-2-win/gobject/Makefile.am.patch
          patch php/Makefile.am ../libguestfs-patches-1.44.2-2-win/php/Makefile.am.patch
          patch daemon/Makefile.am ../libguestfs-patches-1.44.2-2-win/daemon/Makefile.am.patch
          patch lua/Makefile.am ../libguestfs-patches-1.44.2-2-win/lua/Makefile.am.patch
          patch lib/guestfs-internal.h ../libguestfs-patches-1.44.2-2-win/lib/guestfs-internal.h.patch
          patch examples/Makefile.am ../libguestfs-patches-1.44.2-2-win/examples/Makefile.am.patch
          patch lib/match.c ../libguestfs-patches-1.44.2-2-win/lib/match.c.patch
          patch daemon/btrfs.c ../libguestfs-patches-1.44.2-2-win/daemon/btrfs.c.patch
          patch tests/c-api/tests-main.c ../libguestfs-patches-1.44.2-2-win/tests/c-api/tests-main.c.patch
          patch common/mlpcre/pcre-c.c ../libguestfs-patches-1.44.2-2-win/common/mlpcre/pcre-c.c.patch
          patch common/utils/pcre2-cleanups.c ../libguestfs-patches-1.44.2-2-win/common/utils/pcre2-cleanups.c.patch
          patch lib/guestfs-internal-all.h ../libguestfs-patches-1.44.2-2-win/lib/guestfs-internal-all.h.patch
          patch lib/version.c ../libguestfs-patches-1.44.2-2-win/lib/version.c.patch

          rm -rf Makefile.in
          rm -rf generator/Makefile.in

          autoreconf -i

          ./configure --with-qemu="no" --enable-debug --disable-appliance --enable-vala=no --disable-rust --enable-introspection=no --disable-gobject --disable-golang --disable-lua --disable-php --disable-erlang --disable-haskell --disable-ruby --disable-python  --disable-perl --disable-ocaml --disable-libtool-lock --disable-dependency-tracking --disable-option-checking --disable-rust --with-distro=openbsd --disable-probes  --disable-daemon --disable-fuse LDFLAGS="-L/usr/local/lib -L/usr/lib" LIBS="-lintl"

          make CFLAGS="-I/usr/include/ -Wno-error=implicit-function-declaration"

      - name: Compress  
        run: |
          tar -czvf guestfs.tgz .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.tgz
          prerelease: true