name: Windows

on:
  push:
    tags:
      - "augeas-windows-cygwin" 

jobs:
  build:
    runs-on: windows-2019
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe --login -o igncr '{0}'
    strategy:
      matrix:
        arch: [x86_64]
        platform: [windows]
    steps:
      - name: Msgmerge fix
        shell: pwsh 
        run: |
          Remove-Item "C:\Program Files\Git\usr\bin\msgmerge.exe"

      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: wget

      - name: test
        run: |
          pwd

      - name: Install apt-cyg 
        run: |
          wget rawgit.com/transcode-open/apt-cyg/master/apt-cyg -O apt-cyg
          install apt-cyg /bin
     
      - name: Install libs
        run: |
          apt-cyg install gcc-core binutils cmake gcc-g++ automake autoconf libtool gettext-devel libreadline-devel findutils-debuginfo wget libxml2-devel libiconv libiconv-devel 

      - name: Augeas from source code
        run: |
          git clone https://github.com/kymano-app/libguestfs.git
          cd libguestfs
          git clone https://github.com/hercules-team/augeas.git
          cd augeas
          git reset --hard 002b2d5b60c72da6f3326dfec72152b228a8357d
          patch ./src/transform.c  ../augeas-patches/src/transform.c.patch
          ./autogen.sh --prefix=/home/runneradmin/libguestfs/augeas/augeas_package
          make && make install
          tar -czvf augeas-windows.tgz augeas_package/
          mv augeas-windows.tgz ../
          cd ../
          pwd
          ls -l

      - name: pwd
        run: |
          pwd
          ls -l
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.tgz
          prerelease: true