name: Windows

on:
  push:
    tags:
      - "ocaml-windows-cygwin" 

jobs:
  build:
    runs-on: windows-2019
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe --login -o igncr '{0}'
    strategy:
      matrix:
        arch: [x86_64]
        platform: [windows]
    steps:
      - name: Msgmerge fix
        shell: pwsh 
        run: |
          Remove-Item "C:\Program Files\Git\usr\bin\msgmerge.exe"

      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: wget

      - name: test
        run: |
          pwd

      - name: Install apt-cyg 
        run: |
          wget rawgit.com/transcode-open/apt-cyg/master/apt-cyg -O apt-cyg
          install apt-cyg /bin
     
      - name: Install libs for Ocaml
        run: |
          apt-cyg install gcc-core flexdll binutils cmake gcc-g++ automake autoconf libtool python flex bison coreutils opam

      - name: Ocaml from source code
        run: |
          rm -rf /usr/lib/ocaml/
          git clone https://github.com/ocaml/ocaml.git
          cd ocaml
          mkdir ocaml_package
          git checkout 4.14
          git submodule update --init --recursive
          ./configure --enable-imprecise-c99-float-ops --prefix=/home/runneradmin/ocaml/ocaml_package
          make
          make install
          mv ocaml_package ../
          #tar -czvf ocamlwindows.tgz ocaml_package/
          #mv ocamlwindows.tgz ../
          #cd ../
          #pwd
          #ls -l
      
      - name: Compress
        run: |
          tar -czvf ocaml.tgz ocaml/
      
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ocaml.tgz

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ocaml.tgz
          prerelease: true 