name: Windows

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-win" 

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        arch: [x86_64]
        platform: [windows]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Branch name
        id: branch_name
        shell: bash
        run: |
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - uses: msys2/setup-msys2@v2
        with:
          path-type: inherit
          update: true
          install: >-
            git
            cpio
            mingw-w64-x86_64-libarchive
            base-devel
            libtool
            autoconf2.71
            automake1.16
            mingw-w64-x86_64-autotools
            mingw-w64-x86_64-ocaml
            mingw-w64-x86_64-gcc 
            python
            mingw-w64-x86_64-toolchain
            ninja
            mingw-w64-x86_64-diffutils
            xorriso
            mingw-w64-x86_64-file
            mingw-w64-x86_64-jansson
            libiconv
            gettext
            mingw-w64-x86_64-qemu
            coreutils
            po4a
            ncurses-devel
            mingw-w64-x86_64-ncurses
            libtirpc-devel
            mingw-w64-x86_64-pcre2
            mingw-w64-x86_64-libxml2
            findutils

      - name: Find
        if: true
        run: |
          find /usr -name "pwd.h" 
          find /mingw64 -name "pwd.h" 
          # D:\a\_temp\msys64\mingw64\
          ls -l /usr/include/rpc
          ls -l /mingw64/include
          ls -l /mingw64/x86_64-w64-mingw32/include
          ls -l /mingw64/x86_64-w64-mingw32/
          ls -l /mingw64/

          export PKG_CONFIG_PATH=$(pkg-config --variable pc_path pkg-config):/usr/lib/pkgconfig
          /mingw64/bin/pkg-config --list-all
          which pkg-config

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install augeas 
        run: |
          git clone https://github.com/hercules-team/augeas.git
          cd augeas
          git reset --hard 002b2d5b60c72da6f3326dfec72152b228a8357d
          patch ./src/transform.c  ../augeas-patches/src/transform.c.patch
          ./autogen.sh
          make && make install
          cp /usr/local/lib/pkgconfig/augeas.pc /usr/share/pkgconfig/

      - name: Hivex
        run: |
          curl -OL https://download.libguestfs.org/hivex/hivex-1.3.21.tar.gz
          tar -xzf hivex-1.3.21.tar.gz
          cd hivex-1.3.21

          patch ./configure.ac < ../hivex-patches-hivex-1.3.21-2/configure.ac.patch
          patch ./images/Makefile.am < ../hivex-patches-hivex-1.3.21-2/images/Makefile.am.patch

          autoreconf -i --force
          ./configure CFLAGS="-Wno-error=implicit-function-declaration" --disable-ruby --disable-nls --disable-python --disable-perl --disable-ocaml

          make CFLAGS="-v -I/d/a/libguestfs/libguestfs/hivex-1.3.21/gnulib/lib -I/d/a/libguestfs/libguestfs/hivex-1.3.21/ -I/d/a/libguestfs/libguestfs/hivex-1.3.21/lib -Wno-error=implicit-function-declaration"
          make install
    

      - name: Install Libguestfs
        run: |
          export PKG_CONFIG_EXECUTABLE=/mingw64/bin/pkg-config
          export PKG_CONFIG=/mingw64/bin/pkg-config
          export PKG_CONFIG_PATH=$(pkg-config --variable pc_path pkg-config):/usr/lib/pkgconfig

          echo $PKG_CONFIG_EXECUTABLE
          /mingw64/bin/pkg-config --list-all

          ln -s /mingw64/bin/ncursesw6-config /mingw64/bin/ncurses6-config

          git clone https://github.com/kymano-app/libguestfs.git libguestfs_new
          cd libguestfs_new
          curl -OL https://download.libguestfs.org/1.46-stable/libguestfs-1.46.2.tar.gz
          tar -xzf libguestfs-1.46.2.tar.gz
          cd libguestfs-1.46.2

          patch ocaml/examples/Makefile.am ../libguestfs-patches-1.44.2-2/ocaml/examples/Makefile.am.patch
          patch configure.ac ../libguestfs-patches-1.44.2-2/configure.ac.patch
          patch generator/Makefile.am ../libguestfs-patches-1.44.2-2-win/generator/Makefile.am.patch
          patch ocaml/Makefile.am ../libguestfs-patches-1.44.2-2-win/ocaml/Makefile.am.patch
          patch test-data/Makefile.am ../libguestfs-patches-1.44.2-2-win/test-data/Makefile.am.patch
          patch fuse/Makefile.am ../libguestfs-patches-1.44.2-2-win/fuse/Makefile.am.patch
          patch test-tool/Makefile.am ../libguestfs-patches-1.44.2-2-win/test-tool/Makefile.am.patch
          patch fish/Makefile.am ../libguestfs-patches-1.44.2-2-win/fish/Makefile.am.3.patch
          patch ruby/Makefile.am ../libguestfs-patches-1.44.2-2-win/ruby/Makefile.am.patch
          patch bash/Makefile.am ../libguestfs-patches-1.44.2-2-win/bash/Makefile.am.patch
          patch golang/Makefile.am ../libguestfs-patches-1.44.2-2-win/golang/Makefile.am.patch
          patch rescue/Makefile.am ../libguestfs-patches-1.44.2-2-win/rescue/Makefile.am.patch
          patch python/Makefile.am ../libguestfs-patches-1.44.2-2-win/python/Makefile.am.patch
          patch rust/Makefile.am ../libguestfs-patches-1.44.2-2-win/rust/Makefile.am.patch
          patch java/Makefile.am ../libguestfs-patches-1.44.2-2-win/java/Makefile.am.patch
          patch haskell/Makefile.am ../libguestfs-patches-1.44.2-2-win/haskell/Makefile.am.patch
          patch lib/Makefile.am ../libguestfs-patches-1.44.2-2-win/lib/Makefile.am.3.patch
          patch Makefile.am ../libguestfs-patches-1.44.2-2-win/Makefile.am.2.patch
          patch erlang/Makefile.am ../libguestfs-patches-1.44.2-2-win/erlang/Makefile.am.patch
          patch gobject/Makefile.am ../libguestfs-patches-1.44.2-2-win/gobject/Makefile.am.patch
          patch php/Makefile.am ../libguestfs-patches-1.44.2-2-win/php/Makefile.am.patch
          patch daemon/Makefile.am ../libguestfs-patches-1.44.2-2-win/daemon/Makefile.am.patch
          patch lua/Makefile.am ../libguestfs-patches-1.44.2-2-win/lua/Makefile.am.patch
          patch lib/guestfs-internal.h ../libguestfs-patches-1.44.2-2-win/lib/guestfs-internal.h.patch-0.1
          patch examples/Makefile.am ../libguestfs-patches-1.44.2-2-win/examples/Makefile.am.patch
          patch gnulib/lib/getprogname.h ../libguestfs-patches-1.46.2-win/gnulib/lib/getprogname.h.patch
          patch docs/Makefile.am ../libguestfs-patches-1.46.2-win/docs/Makefile.am.patch
          patch lib/launch-direct.c ../libguestfs-patches-1.46.2-win/lib/launch-direct.c.patch
          patch m4/guestfs-libraries.m4 ../libguestfs-patches-1.46.2-win-mingw/m4/guestfs-libraries.m4.patch
          patch fish/rc.c ../libguestfs-patches-1.46.2-win/fish/rc.c.patch
          patch lib/launch-unix.c ../libguestfs-patches-1.46.2-win/lib/launch-unix.c.patch
          patch lib/launch-libvirt.c ../libguestfs-patches-1.46.2-win/lib/launch-libvirt.c.patch

          autoreconf -i

          ./configure --with-qemu="no" --enable-debug --disable-appliance --enable-vala=no --disable-rust --enable-introspection=no --disable-gobject --disable-golang --disable-lua --disable-php --disable-erlang --disable-haskell --disable-ruby --disable-python  --disable-perl --enable-ocaml --disable-libtool-lock --disable-dependency-tracking --disable-option-checking --disable-rust --with-distro=openbsd --disable-probes  --disable-daemon --disable-fuse 
          LDFLAGS="-L/mingw64/lib/ -L/usr/lib/" LIBS="-lintl -lpcre2-8 -ljansson -ltirpc" CFLAGS="-I/mingw64/x86_64-w64-mingw32/include/ -I/mingw64/include/ -I/usr/include/" CPPFLAGS="-I/usr/include/"

          make CFLAGS="-I/usr/include/ -I/usr/lib/ocaml/" --trace

          ./run guestfish --help

      - name: Find
        if: false
        shell: pwsh 
        run: |
          D:\a\_temp\msys64\usr\share\bash-completion\completions\cpio --help
          D:\a\_temp\msys64\usr\share\perl5\core_perl\IO\Compress\zip
