name: Windows

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-win" 

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86_64]
        platform: [windows]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Branch name
        id: branch_name
        shell: bash
        run: |
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - uses: msys2/setup-msys2@v2
        with:
          path-type: inherit
          update: true
          install: >-
            git
            cpio
            mingw-w64-x86_64-libarchive

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
    
      - name: Build
        run: |
          pwd
     
      - name: Find
        run: |
          git --help
          cpio --help
     
      - name: Find
        shell: pwsh 
        run: |
          D:\a\_temp\msys64\usr\share\bash-completion\completions\cpio --help
          D:\a\_temp\msys64\usr\share\perl5\core_perl\IO\Compress\zip

      - name: Find
        if: false
        shell: pwsh 
        run: |
          Get-ChildItem -Path D:\ -Filter zip.* -Recurse -ErrorAction SilentlyContinue -Force

      - name: Build
        run: |
          pwd
          pacman -Suy --noconfirm
          pacman -Sy --noconfirm mingw-w64-x86_64-libarchive
          pacman -Sy --noconfirm base-devel
          pacman -Sy --noconfirm libtool
          pacman -Sy --noconfirm autoconf2.71
          pacman -Sy --noconfirm automake1.16
          pacman -Sy --noconfirm mingw-w64-x86_64-autotools
          pacman -Sy --noconfirm mingw-w64-x86_64-ocaml
          pacman -Sy --noconfirm mingw-w64-x86_64-gcc 
          pacman -Sy --noconfirm python
          pacman -Sy --noconfirm mingw-w64-x86_64-toolchain
          pacman -Sy --noconfirm ninja
          pacman -Sy --noconfirm mingw-w64-x86_64-diffutils
          pacman -Sy --noconfirm xorriso
          pacman -Sy --noconfirm mingw-w64-x86_64-file
          pacman -Sy --noconfirm mingw-w64-x86_64-jansson
          pacman -Sy --noconfirm libiconv
          pacman -Sy --noconfirm gettext
          pacman -Sy --noconfirm mingw-w64-x86_64-qemu
          pacman -Sy --noconfirm coreutils
          pacman -Sy --noconfirm po4a
          pacman -Sy --noconfirm ncurses
          pacman -Ss

      - name: Hivex
        run: |
          curl -OL https://download.libguestfs.org/hivex/hivex-1.3.21.tar.gz
          tar -xzf hivex-1.3.21.tar.gz
          cd hivex-1.3.21

          patch ./configure.ac < ../hivex-patches-hivex-1.3.21-2/configure.ac.patch
          patch ./images/Makefile.am < ../hivex-patches-hivex-1.3.21-2/images/Makefile.am.patch

          autoreconf -i --force
          ./configure CFLAGS="-Wno-error=implicit-function-declaration" --disable-ruby --disable-nls --disable-python --disable-perl --disable-ocaml
          echo ":::::::::::::::::::::::::::::::make" 

          make CFLAGS="-v -I/d/a/libguestfs/libguestfs/hivex-1.3.21/gnulib/lib -I/d/a/libguestfs/libguestfs/hivex-1.3.21/ -I/d/a/libguestfs/libguestfs/hivex-1.3.21/lib -Wno-error=implicit-function-declaration"
          echo ":::::::::::::::::::::::::::::::make install"
          make install

      - name: Install
        run: |
          curl -OL https://download.libguestfs.org/1.44-stable/libguestfs-1.44.2.tar.gz
          tar -xzf libguestfs-1.44.2.tar.gz
          cd libguestfs-1.44.2

          patch align/Makefile.am < ../libguestfs-patches-1.44.2-2/align/Makefile.am.patch
          patch cat/Makefile.am < ../libguestfs-patches-1.44.2-2/cat/Makefile.am.patch
          patch common/mlpcre/pcre-c.c < ../libguestfs-patches-1.44.2-2/common/mlpcre/pcre-c.c.patch
          patch common/protocol/guestfs_protocol.c < ../libguestfs-patches-1.44.2-2/common/protocol/guestfs_protocol.c.patch
          patch df/Makefile.am < ../libguestfs-patches-1.44.2-2/df/Makefile.am.patch
          patch diff/Makefile.am < ../libguestfs-patches-1.44.2-2/diff/Makefile.am.patch
          patch docs/Makefile.am < ../libguestfs-patches-1.44.2-2/docs/Makefile.am.patch
          patch edit/Makefile.am < ../libguestfs-patches-1.44.2-2/edit/Makefile.am.patch
          patch examples/Makefile.am < ../libguestfs-patches-1.44.2-2/examples/Makefile.am.patch
          patch fish/Makefile.am < ../libguestfs-patches-1.44.2-2/fish/Makefile.am.patch
          patch format/Makefile.am < ../libguestfs-patches-1.44.2-2/format/Makefile.am.patch
          patch gobject/Makefile.am < ../libguestfs-patches-1.44.2-2/gobject/Makefile.am.patch
          patch inspector/Makefile.am < ../libguestfs-patches-1.44.2-2/inspector/Makefile.am.patch
          patch lib/Makefile.am < ../libguestfs-patches-1.44.2-2/lib/Makefile.am.patch
          patch lib/inspect-apps.c < ../libguestfs-patches-1.44.2-2/lib/inspect-apps.c.patch
          patch m4/guestfs-progs.m4 < ../libguestfs-patches-1.44.2-2/m4/guestfs-progs.m4.patch
          patch make-fs/Makefile.am < ../libguestfs-patches-1.44.2-2/make-fs/Makefile.am.patch
          patch ocaml/examples/Makefile.am < ../libguestfs-patches-1.44.2-2/ocaml/examples/Makefile.am.patch
          patch rescue/Makefile.am < ../libguestfs-patches-1.44.2-2/rescue/Makefile.am.patch
          patch test-tool/Makefile.am < ../libguestfs-patches-1.44.2-2/test-tool/Makefile.am.patch
          patch test-tool/test-tool.c < ../libguestfs-patches-1.44.2-2/test-tool/test-tool.c.patch
          patch configure.ac < ../libguestfs-patches-1.44.2-2/configure.ac.patch
          patch Makefile.am < ../libguestfs-patches-1.44.2-2/Makefile.am.patch

          autoreconf -i
          ./configure --enable-debug --disable-appliance --enable-vala=no --disable-rust --enable-introspection=no --disable-gobject --disable-golang --disable-lua --disable-php --disable-erlang --disable-haskell --disable-ruby --disable-python  --disable-perl --disable-ocaml --disable-libtool-lock --disable-dependency-tracking --disable-option-checking --disable-rust --with-distro=openbsd --disable-probes  --disable-daemon --disable-fuse

          make -Wno-error=implicit-function-declaration"