name: Windows

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-sygwin" 

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [x86_64]
        platform: [windows]
    steps:
      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: cmake gcc-g++ cpio xorriso augeas libmagic jansson automake libiconv gettext ocaml opam ocaml-findlib coreutils osxfuse autoconf po4a ncurses libtool mingw-w64-x86_64-libarchive base-devel mingw-w64-x86_64-autotools mingw-w64-x86_64-ocaml mingw-w64-x86_64-gcc mingw-w64-x86_64-qemu python mingw-w64-x86_64-toolchain ninja mingw-w64-x86_64-diffutils mingw-w64-x86_64-file mingw-w64-x86_64-jansson

      - name: Hivex
        run: |
          curl -OL https://download.libguestfs.org/hivex/hivex-1.3.21.tar.gz
          tar -xzf hivex-1.3.21.tar.gz
          cd hivex-1.3.21

          patch ./configure.ac  ../hivex-patches-hivex-1.3.21-2/configure.ac.patch
          patch ./images/Makefile.am  ../hivex-patches-hivex-1.3.21-2/images/Makefile.am.patch

          autoreconf -i --force
          ./configure CFLAGS="-Wno-error=implicit-function-declaration" --disable-ruby --disable-nls --disable-python --disable-perl --disable-ocaml

          make CFLAGS="-v -I/d/a/libguestfs/libguestfs/hivex-1.3.21/gnulib/lib -I/d/a/libguestfs/libguestfs/hivex-1.3.21/ -I/d/a/libguestfs/libguestfs/hivex-1.3.21/lib -Wno-error=implicit-function-declaration"
          make install
