name: Windows

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-win" 

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86_64]
        platform: [windows]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Branch name
        id: branch_name
        shell: bash
        run: |
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        run: |
          BUILD_PATH=$HOME/QEMU-bin
          mkdir bin
          pacman -Suy --noconfirm
          pacman -Sy --noconfirm mingw-w64-x86_64-gcc python
          pacman -Sy --noconfirm mingw-w64-x86_64-toolchain
          pacman -Sy --noconfirm ninja
          pacman -Sy --noconfirm mingw-w64-x86_64-diffutils
          pacman -Sy --noconfirm mingw-w64-x86_64-xorriso
          pacman -Sy --noconfirm mingw-w64-x86_64-file
          pacman -Sy --noconfirm mingw-w64-jansson
          pacman -Sy --noconfirm mingw-w64-libiconv
          pacman -Sy --noconfirm mingw-w64-gettext
          pacman -Sy --noconfirm mingw-w64-qemu
          pacman -Sy --noconfirm mingw-w64-ocaml
          pacman -Sy --noconfirm coreutils
          pacman -Sy --noconfirm autoconf2.71
          pacman -Sy --noconfirm po4a
          pacman -Sy --noconfirm mingw-w64-ncurses
        
      - name: Hivex
        run: |
          curl -OL https://download.libguestfs.org/hivex/hivex-1.3.21.tar.gz
          tar -xzf hivex-1.3.21.tar.gz
          cd hivex-1.3.21
          patch ./configure.ac < ../hivex-patches-hivex-1.3.21-2/configure.ac.patch
          autoreconf -i --force
          ./configure CFLAGS="-Wno-error=implicit-function-declaration"  --with-libintl-prefix=/usr/local/ --disable-ruby --disable-nls --disable-python --disable-perl --disable-ocaml --prefix=/opt/local/
          make CFLAGS="-Wno-error=implicit-function-declaration" WERROR_CFLAGS="-Wno-error=implicit-function-declaration"
          sudo make install
