name: Windows

on:
  push:
    tags:
      - "hivex-windows" 

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        arch: [x86_64]
        platform: [windows]
    defaults:
      run:
        shell: msys2 {0} 
    steps:
      - name: Branch name
        id: branch_name
        shell: bash
        run: |
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - uses: msys2/setup-msys2@v2
        with:
          path-type: inherit
          update: true
          install: >-
            git
            cpio
            mingw-w64-x86_64-libarchive
            base-devel
            libtool
            autoconf2.71
            automake1.16
            mingw-w64-x86_64-autotools
            mingw-w64-x86_64-ocaml
            mingw-w64-x86_64-gcc 
            python
            mingw-w64-x86_64-toolchain
            ninja
            mingw-w64-x86_64-diffutils
            xorriso
            mingw-w64-x86_64-file
            mingw-w64-x86_64-jansson
            libiconv
            gettext
            mingw-w64-x86_64-qemu
            coreutils
            po4a
            ncurses-devel
            mingw-w64-x86_64-ncurses
            libtirpc-devel
            mingw-w64-x86_64-pcre2
            mingw-w64-x86_64-libxml2
            findutils

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Hivex from source code
        run: |
          rm -rf /usr/lib/ocaml/
          git clone https://github.com/ocaml/ocaml.git
          cd ocaml
          git checkout 4.14
          git submodule update --init --recursive
          ./configure --enable-imprecise-c99-float-ops --prefix=/usr
          make
          make install

      - name: Release
        if: false
        uses: softprops/action-gh-release@v1
        with:
          files: |
            hivex-windows.tgz
          prerelease: true