name: Windows

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-cygwin" 

jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe --login -o igncr '{0}'
    strategy:
      matrix:
        arch: [x86_64]
        platform: [windows]
    steps:
      - name: Msgmerge fix
        shell: pwsh 
        run: |
          Remove-Item "C:\Program Files\Git\usr\bin\msgmerge.exe"

      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: wget

      - name: Install apt-cyg 
        run: |
          wget rawgit.com/transcode-open/apt-cyg/master/apt-cyg -O apt-cyg
          install apt-cyg /bin

      - name: Install libs for Hivex
        run: |
          apt-cyg install cmake gcc-g++ cpio automake libiconv libiconv-devel gettext opam ocaml-findlib coreutils autoconf po4a ncurses libtool python ninja genisoimage flex bison byacc libncurses-devel git mingw64-x86_64-gettext lynx gperf

      - name: Install ocaml
        run: |
          git clone https://github.com/ocaml/ocaml.git
          cd ocaml
          gi checkout 4.14
          git submodule update --init --recursive
          ./configure
          make
          make install

      - name: Install Hivex 
        run: |
          pkg-config --variable pc_path pkg-config

          git clone https://github.com/kymano-app/libguestfs.git
          cd libguestfs
          curl -OL https://download.libguestfs.org/hivex/hivex-1.3.21.tar.gz
          tar -xzf hivex-1.3.21.tar.gz
          cd hivex-1.3.21
          
          rm -rf ./aclocal.m4
          aclocal
          
          patch ./images/Makefile.am  ../hivex-patches-hivex-1.3.21-2/images/Makefile.am.patch
          autoreconf -i --force
          
          ./configure CFLAGS="-Wno-error=implicit-function-declaration" --disable-ruby --disable-nls --disable-python --disable-perl --disable-ocaml

          make CFLAGS="-v -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/ -I/home/runneradmin/hivex-1.3.21/gnulib/lib -I/home/runneradmin/hivex-1.3.21/ -I/home/runneradmin/hivex-1.3.21/lib -Wno-error=implicit-function-declaration"
          make install

          cp /usr/local/lib/pkgconfig/hivex.pc /usr/share/pkgconfig/
      
      - name: Install libs for Augeas
        run: |
          apt-cyg install gettext-devel libtirpc-devel libreadline-devel libxml2-devel findutils-debuginfo wget

      - name: Install augeas 
        run: |
          cd libguestfs
          git clone https://github.com/hercules-team/augeas.git
          cd augeas
          git reset --hard 002b2d5b60c72da6f3326dfec72152b228a8357d
          patch ./src/transform.c  ../augeas-patches/src/transform.c.patch
          ./autogen.sh
          make && make install
          cp /usr/local/lib/pkgconfig/augeas.pc /usr/share/pkgconfig/

      - name: Install libs for Libguestfs
        run: |
          apt-cyg install file-devel libjansson-devel

      - name: Install Libguestfs
        run: |
          cd libguestfs

          curl -OL https://download.libguestfs.org/1.44-stable/libguestfs-1.44.2.tar.gz
          tar -xzf libguestfs-1.44.2.tar.gz
          cd libguestfs-1.44.2

          patch align/Makefile.am ../libguestfs-patches-1.44.2-2/align/Makefile.am.patch
          patch cat/Makefile.am ../libguestfs-patches-1.44.2-2/cat/Makefile.am.patch
          patch common/mlpcre/pcre-c.c ../libguestfs-patches-1.44.2-2/common/mlpcre/pcre-c.c.patch
          patch common/protocol/guestfs_protocol.c ../libguestfs-patches-1.44.2-2/common/protocol/guestfs_protocol.c.patch
          patch df/Makefile.am ../libguestfs-patches-1.44.2-2/df/Makefile.am.patch
          patch diff/Makefile.am ../libguestfs-patches-1.44.2-2/diff/Makefile.am.patch
          patch docs/Makefile.am ../libguestfs-patches-1.44.2-2/docs/Makefile.am.patch
          patch edit/Makefile.am ../libguestfs-patches-1.44.2-2/edit/Makefile.am.patch
          patch examples/Makefile.am ../libguestfs-patches-1.44.2-2/examples/Makefile.am.patch
          patch fish/Makefile.am ../libguestfs-patches-1.44.2-2/fish/Makefile.am.patch
          patch format/Makefile.am ../libguestfs-patches-1.44.2-2/format/Makefile.am.patch
          patch gobject/Makefile.am ../libguestfs-patches-1.44.2-2/gobject/Makefile.am.patch
          patch inspector/Makefile.am ../libguestfs-patches-1.44.2-2/inspector/Makefile.am.patch
          patch lib/Makefile.am ../libguestfs-patches-1.44.2-2/lib/Makefile.am.patch
          patch lib/inspect-apps.c ../libguestfs-patches-1.44.2-2/lib/inspect-apps.c.patch
          patch m4/guestfs-progs.m4 ../libguestfs-patches-1.44.2-2/m4/guestfs-progs.m4.patch
          patch make-fs/Makefile.am ../libguestfs-patches-1.44.2-2/make-fs/Makefile.am.patch
          patch ocaml/examples/Makefile.am ../libguestfs-patches-1.44.2-2/ocaml/examples/Makefile.am.patch
          patch rescue/Makefile.am ../libguestfs-patches-1.44.2-2/rescue/Makefile.am.patch
          patch test-tool/Makefile.am ../libguestfs-patches-1.44.2-2/test-tool/Makefile.am.patch
          patch test-tool/test-tool.c ../libguestfs-patches-1.44.2-2/test-tool/test-tool.c.patch
          patch configure.ac ../libguestfs-patches-1.44.2-2/configure.ac.patch
          patch Makefile.am ../libguestfs-patches-1.44.2-2/Makefile.am.patch

          autoreconf -i
          ./configure --with-qemu="no" --enable-debug --disable-appliance --enable-vala=no --disable-rust --enable-introspection=no --disable-gobject --disable-golang --disable-lua --disable-php --disable-erlang --disable-haskell --disable-ruby --disable-python  --disable-perl --disable-ocaml --disable-libtool-lock --disable-dependency-tracking --disable-option-checking --disable-rust --with-distro=openbsd --disable-probes  --disable-daemon --disable-fuse LDFLAGS="-L/usr/local/lib" LIBS="-lintl"

          make CFLAGS="-I/usr/x86_64-w64-mingw32/sys-root/mingw/include -Wno-error=implicit-function-declaration"

          make install