name: Windows

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-win" 

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86_64]
        platform: [windows]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Branch name
        id: branch_name
        shell: bash
        run: |
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        run: |
          pwd
          pacman -Suy --noconfirm
          pacman -Sy --noconfirm base-devel
          pacman -Sy --noconfirm libtool
          pacman -Sy --noconfirm autoconf2.71
          pacman -Sy --noconfirm automake1.16
          pacman -Sy --noconfirm mingw-w64-x86_64-autotools
          pacman -Sy --noconfirm mingw-w64-x86_64-ocaml
          pacman -Sy --noconfirm mingw-w64-x86_64-gcc 
          pacman -Sy --noconfirm python
          pacman -Sy --noconfirm mingw-w64-x86_64-toolchain
          pacman -Sy --noconfirm ninja
          pacman -Sy --noconfirm mingw-w64-x86_64-diffutils
          pacman -Sy --noconfirm xorriso
          pacman -Sy --noconfirm mingw-w64-x86_64-file
          pacman -Sy --noconfirm mingw-w64-x86_64-jansson
          pacman -Sy --noconfirm libiconv
          pacman -Sy --noconfirm gettext
          pacman -Sy --noconfirm mingw-w64-x86_64-qemu
          pacman -Sy --noconfirm coreutils
          pacman -Sy --noconfirm po4a
          pacman -Sy --noconfirm ncurses
          pacman -Ss

      - name: Hivex
        run: |
          curl -OL https://download.libguestfs.org/hivex/hivex-1.3.21.tar.gz
          tar -xzf hivex-1.3.21.tar.gz
          cd hivex-1.3.21

          patch ./configure.ac < ../hivex-patches-hivex-1.3.21-2/configure.ac.patch
          patch ./images/Makefile.am < ../hivex-patches-hivex-1.3.21-2/images/Makefile.am.patch
          
          autoreconf -i --force
          ./configure CFLAGS="-Wno-error=implicit-function-declaration" --disable-ruby --disable-nls --disable-python --disable-perl --disable-ocaml
          echo ":::::::::::::::::::::::::::::::make" 

          make CFLAGS="-v -I/d/a/libguestfs/libguestfs/hivex-1.3.21/gnulib/lib -I/d/a/libguestfs/libguestfs/hivex-1.3.21/ -I/d/a/libguestfs/libguestfs/hivex-1.3.21/lib -Wno-error=implicit-function-declaration"
          echo ":::::::::::::::::::::::::::::::make install"
          sudo make install
