name: Windows

on:
  push:
    tags:
      - "ocaml-windows-cygwin" 

jobs:
  build:
    runs-on: windows-2019
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe --login -o igncr '{0}'
    strategy:
      matrix:
        arch: [x86_64]
        platform: [windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Msgmerge fix
        shell: pwsh 
        run: |
          Remove-Item "C:\Program Files\Git\usr\bin\msgmerge.exe"

      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: wget
      
      - name: test
        run: |
          pwd

      - name: Install apt-cyg 
        run: |
          wget rawgit.com/transcode-open/apt-cyg/master/apt-cyg -O apt-cyg
          install apt-cyg /bin
          echo 'ddygiiuhmDfdfdfdd' > ddygiiuhmDfdfdfdd
      
      - name: Dir 
        shell: pwsh 
        run: |
          dir C:\tools\cygwin\home\runneradmin\

      - name: Install libs for Ocaml
        run: |
          apt-cyg install gcc-core flexdll binutils cmake gcc-g++ automake autoconf libtool python flex bison coreutils opam

      - name: Ocaml from source code
        run: |
          rm -rf /usr/lib/ocaml/
          git clone https://github.com/ocaml/ocaml.git
          cd ocaml
          mkdir ocaml_package
          mkdir ocaml_package/bin
          mkdir ocaml_package/lib
          git checkout 4.14
          git submodule update --init --recursive
          ./configure --enable-imprecise-c99-float-ops --prefix=/usr
          make
          make install
          find /usr/bin -name "*ocaml*" | while read f ; do true | cp $f ocaml_package/bin/; done
          find /usr/bin -name "*flex*" | while read f ; do true | cp $f ocaml_package/bin/; done
          cp -r /usr/lib/ocaml ocaml_package/lib/
          cp -r /usr/lib/ocaml ocaml_package/lib/
          tar -czvf ocaml_windows.tgz ocaml_package/
          mv ocaml_windows.tgz ../
          cd ../
          pwd
          ls -l 
      
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: C:\tools\cygwin\home\runneradmin\ocaml_windows.tgz

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: C:\tools\cygwin\home\runneradmin\ocaml_windows.tgz
          prerelease: true  