name: Macos

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]"

jobs:
  build-macos-ports:
    name: Build0
    runs-on: macos-11
    strategy:
      matrix:
        arch: [x86_64]
        platform: [macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Brew Install
        run: |
           brew install xorriso augeas libmagic jansson automake libiconv gettext
           brew install qemu ocaml opam ocaml-findlib coreutils

      - name: Macports
        run: |
           wget https://github.com/macports/macports-base/releases/download/v2.7.1/MacPorts-2.7.1-11-BigSur.pkg
           sudo installer -pkg ./MacPorts-2.7.1-11-BigSur.pkg -target /

      - name: Macports Install
        run: |
          # sudo chown runner /opt/local/etc/macports/macports.conf 
          # sudo echo 'build_arch arm64' >> /opt/local/etc/macports/macports.conf
          export PATH="/opt/local/bin:$PATH"
          sudo port install autoconf po4a magic
          sudo port install ncurses
          sudo port install binutils

      # - name: Hivex
      #   run: |
      #     export LDFLAGS="-L/usr/local/opt/libiconv/lib"
      #     export CPPFLAGS="-I/usr/local/opt/libiconv/include"
      #     export CFLAGS="$CFLAGS -std=c90"
      #     #find / -name "libintl.h" 2>/dev/null
      #     curl -OL https://download.libguestfs.org/hivex/hivex-1.3.21.tar.gz
      #     tar -xzf hivex-1.3.21.tar.gz
      #     cd hivex-1.3.21
      #     rm -rf xml
      #     patch ./configure.ac < ../hivex-patches/configure.ac.patch
      #     patch ./Makefile.am < ../hivex-patches/Makefile.am.patch
      #     patch ./run.in < ../hivex-patches/run.in.patch
      #     patch ./configure < ../hivex-patches/configure.patch
      #     patch ./m4/00gnulib.m4 < ../hivex-patches/00gnulib.m4.patch
      #     CC="gcc -m64" ./configure --with-libintl-prefix=/usr/local/ --disable-ruby --disable-nls --disable-python --disable-perl CC="gcc -std=c90" 
      #     make

      - name: Libguestfs Install
        run: |
          # curl -OL https://download.libguestfs.org/1.46-stable/libguestfs-1.46.2.tar.gz
          # tar -xzf libguestfs-1.46.2.tar.gz
          # cd libguestfs-1.46.2
          # ./configure --enable-daemon=no
          # make
          ls -l
          git clone https://github.com/libguestfs/libguestfs
          cd libguestfs
          patch ./generator/Makefile.am < ../libguestfs-patches/generator/Makefile.am.patch
          patch ./generator/actions.ml < ../libguestfs-patches/generator/actions.ml.patch
          patch ./generator/proc_nr.ml < ../libguestfs-patches/generator/proc_nr.ml.patch
          patch ./daemon/Makefile.am < ../libguestfs-patches/daemon/Makefile.am.patch
          patch ./gobject/Makefile.inc < ../libguestfs-patches/gobject/Makefile.inc.patch
          patch ./java/Makefile.inc < ../libguestfs-patches/java/Makefile.inc.patch
          patch ./m4/guestfs-ocaml.m4 < ../libguestfs-patches/m4/guestfs-ocaml.m4.patch
          patch ./m4/guestfs-daemon.m4 < ../libguestfs-patches/m4/guestfs-daemon.m4.patch
          patch ./podwrapper.pl.in < ../libguestfs-patches/podwrapper.pl.in.patch
          patch ./examples/Makefile.am < ../libguestfs-patches/examples/Makefile.am.patch
         
          git submodule update --init
          autoreconf -i
          ./configure --help
          export CFLAGS="-Wno-error"
          export CXXFLAGS="-Wno-error"

          ./configure LIBTINFO_CFLAGS=-Wno-error CFLAGS="-fPIC -Wno-error" LIBCONFIG_CFLAGS=-Wno-error RPC_CFLAGS=-Wno-error  GOBJECT_CFLAGS=-Wno-error BASH_COMPLETION_CFLAGS=-Wno-error  GIO_CFLAGS=-Wno-error CXXFLAGS=-Wno-error --enable-vala=no --disable-rust --enable-introspection=no --disable-gobject --disable-golang --disable-lua --disable-php --disable-erlang --disable-haskell --disable-ruby --disable-python  --disable-perl --disable-ocaml --disable-libtool-lock --disable-dependency-tracking --disable-option-checking --disable-rust --with-distro=openbsd --enable-daemon=no --disable-daemon --disable-appliance --exec-prefix=/opt/local/
          make CFLAGS=-Wno-error

      - name: Compress
        run: |
          tar -czvf g.tgz libs bin share

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.tgz
          prerelease: true