name: Windows

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-cygwin" 

jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe --login -o igncr '{0}'
    strategy:
      matrix:
        arch: [x86_64]
        platform: [windows]
    steps:
      - name: Fix
        shell: pwsh 
        run: |
          Remove-Item "C:\Program Files\Git\usr\bin\msgmerge.exe"

      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: cmake gcc-g++ cpio xorriso augeas libmagic jansson automake libiconv libiconv-devel gettext ocaml opam ocaml-findlib coreutils osxfuse autoconf po4a ncurses libtool mingw-w64-x86_64-libarchive base-devel mingw-w64-x86_64-autotools mingw-w64-x86_64-ocaml mingw-w64-x86_64-gcc mingw-w64-x86_64-qemu python mingw-w64-x86_64-toolchain ninja mingw-w64-x86_64-diffutils mingw-w64-x86_64-file mingw-w64-x86_64-jansson gperf genisoimage flex bison byacc libncurses-devel git gettext-devel mingw64-x86_64-gettext
      
      - name: find 
        run: |
          ls -l /usr/x86_64-w64-mingw32/sys-root/mingw/include/

      - name: Hivex 
        run: |
        
          pwd
          msgmerge --help
          git clone https://github.com/kymano-app/libguestfs.git
          cd libguestfs
          curl -OL https://download.libguestfs.org/hivex/hivex-1.3.21.tar.gz
          tar -xzf hivex-1.3.21.tar.gz
          cd hivex-1.3.21
          
          rm -rf ./aclocal.m4
          aclocal
          
          patch ./images/Makefile.am  ../hivex-patches-hivex-1.3.21-2/images/Makefile.am.patch

          autoreconf -i --force

          ./configure CFLAGS="-Wno-error=implicit-function-declaration" --disable-ruby --disable-nls --disable-python --disable-perl --disable-ocaml --with-libintl-prefix=/usr/local/

          make CFLAGS="-v -I/usr/include/ -I/d/a/libguestfs/libguestfs/hivex-1.3.21/gnulib/lib -I/d/a/libguestfs/libguestfs/hivex-1.3.21/ -I/d/a/libguestfs/libguestfs/hivex-1.3.21/lib -Wno-error=implicit-function-declaration"
          make install
      - name: Install
        run: |
          cd libguestfs
          pwd
          ls -l

          curl -OL https://download.libguestfs.org/1.44-stable/libguestfs-1.44.2.tar.gz
          tar -xzf libguestfs-1.44.2.tar.gz
          cd libguestfs-1.44.2

          patch align/Makefile.am ../libguestfs-patches-1.44.2-2/align/Makefile.am.patch
          patch cat/Makefile.am ../libguestfs-patches-1.44.2-2/cat/Makefile.am.patch
          patch common/mlpcre/pcre-c.c ../libguestfs-patches-1.44.2-2/common/mlpcre/pcre-c.c.patch
          patch common/protocol/guestfs_protocol.c ../libguestfs-patches-1.44.2-2/common/protocol/guestfs_protocol.c.patch
          patch df/Makefile.am ../libguestfs-patches-1.44.2-2/df/Makefile.am.patch
          patch diff/Makefile.am ../libguestfs-patches-1.44.2-2/diff/Makefile.am.patch
          patch docs/Makefile.am ../libguestfs-patches-1.44.2-2/docs/Makefile.am.patch
          patch edit/Makefile.am ../libguestfs-patches-1.44.2-2/edit/Makefile.am.patch
          patch examples/Makefile.am ../libguestfs-patches-1.44.2-2/examples/Makefile.am.patch
          patch fish/Makefile.am ../libguestfs-patches-1.44.2-2/fish/Makefile.am.patch
          patch format/Makefile.am ../libguestfs-patches-1.44.2-2/format/Makefile.am.patch
          patch gobject/Makefile.am ../libguestfs-patches-1.44.2-2/gobject/Makefile.am.patch
          patch inspector/Makefile.am ../libguestfs-patches-1.44.2-2/inspector/Makefile.am.patch
          patch lib/Makefile.am ../libguestfs-patches-1.44.2-2/lib/Makefile.am.patch
          patch lib/inspect-apps.c ../libguestfs-patches-1.44.2-2/lib/inspect-apps.c.patch
          patch m4/guestfs-progs.m4 ../libguestfs-patches-1.44.2-2/m4/guestfs-progs.m4.patch
          patch make-fs/Makefile.am ../libguestfs-patches-1.44.2-2/make-fs/Makefile.am.patch
          patch ocaml/examples/Makefile.am ../libguestfs-patches-1.44.2-2/ocaml/examples/Makefile.am.patch
          patch rescue/Makefile.am ../libguestfs-patches-1.44.2-2/rescue/Makefile.am.patch
          patch test-tool/Makefile.am ../libguestfs-patches-1.44.2-2/test-tool/Makefile.am.patch
          patch test-tool/test-tool.c ../libguestfs-patches-1.44.2-2/test-tool/test-tool.c.patch
          patch configure.ac ../libguestfs-patches-1.44.2-2/configure.ac.patch
          patch Makefile.am ../libguestfs-patches-1.44.2-2/Makefile.am.patch

          autoreconf -i
          ./configure --enable-debug --disable-appliance --enable-vala=no --disable-rust --enable-introspection=no --disable-gobject --disable-golang --disable-lua --disable-php --disable-erlang --disable-haskell --disable-ruby --disable-python  --disable-perl --disable-ocaml --disable-libtool-lock --disable-dependency-tracking --disable-option-checking --disable-rust --with-distro=openbsd --disable-probes  --disable-daemon --disable-fuse

          make -Wno-error=implicit-function-declaration"

          make install