name: Windows

on:
  push:
    tags:
      - "hivex-windows" 

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        arch: [x86_64]
        platform: [windows]
    defaults:
      run:
        shell: msys2 {0} 
    steps:
      - name: Branch name
        id: branch_name
        shell: bash
        run: |
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - uses: msys2/setup-msys2@v2
        with:
          path-type: inherit
          update: true
          install: >-
            git
            cpio
            mingw-w64-x86_64-libarchive
            base-devel
            libtool
            autoconf2.71
            automake1.16
            mingw-w64-x86_64-autotools
            mingw-w64-x86_64-ocaml
            mingw-w64-x86_64-gcc 
            python
            mingw-w64-x86_64-toolchain
            ninja
            mingw-w64-x86_64-diffutils
            xorriso
            mingw-w64-x86_64-file
            mingw-w64-x86_64-jansson
            libiconv
            gettext
            mingw-w64-x86_64-qemu
            coreutils
            po4a
            ncurses-devel
            mingw-w64-x86_64-ncurses
            libtirpc-devel
            mingw-w64-x86_64-pcre2
            mingw-w64-x86_64-libxml2
            findutils

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Hivex from source code
        run: |
          curl -OL https://download.libguestfs.org/hivex/hivex-1.3.21.tar.gz
          tar -xzf hivex-1.3.21.tar.gz
          cd hivex-1.3.21
          mkdir hivex_package

          patch ./configure.ac < ../hivex-patches-hivex-1.3.21-2/configure.ac.patch
          patch ./images/Makefile.am < ../hivex-patches-hivex-1.3.21-2/images/Makefile.am.patch

          autoreconf -i --force
          ./configure CFLAGS="-Wno-error=implicit-function-declaration" --disable-ruby --disable-nls --disable-python --disable-perl --disable-ocaml --prefix="/d/a/libguestfs/libguestfs/hivex-1.3.21/hivex_package"

          make CFLAGS="-v -I/d/a/libguestfs/libguestfs/hivex-1.3.21/gnulib/lib -I/d/a/libguestfs/libguestfs/hivex-1.3.21/ -I/d/a/libguestfs/libguestfs/hivex-1.3.21/lib -Wno-error=implicit-function-declaration"
          make install
          tar -czvf hivex-windows.tgz hivex_package/
          mv hivex-windows.tgz ../

      - name: Release
        if: false
        uses: softprops/action-gh-release@v1
        with:
          files: |
            hivex-windows.tgz
          prerelease: true